name: Build and deploy Node.js project to Azure Function App - httptriggernch

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_FUNCTIONAPP_PACKAGE_PATH: './myFunctionApp'
  NODE_VERSION: '20.x'

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read
      
    steps:
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@v4

      - name: Setup Node ${{ env.NODE_VERSION }} Environment
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: 'Resolve Project Dependencies Using Npm'
        shell: pwsh
        run: |
          pushd './myFunctionApp'
          npm install
          popd

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./myFunctionApp   

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_035E102F54624CBA9218E454B8271C17 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_B12579310C5A40089B0C640169DAFADE }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_587549F8BE9E4903A08BD13D8E7608D4 }}

      - name: 'Run Azure Functions Action'
        uses: Azure/functions-action@v1
        id: fa
        with:
          app-name: 'httptriggernch'
          slot-name: 'Production'
          package: .